main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('sneakers/', views.sneakers_index, name='index'),
    path('sneakers/<int:sneaker_id>/', views.sneakers_detail, name='detail'),
    path('sneakers/create/', views.SneakerCreate.as_view(), name='sneakers_create'),
    path('sneakers/<int:pk>/update/', views.SneakerUpdate.as_view(), name='sneakers_update'),
    path('sneakers/<int:pk>/delete/', views.SneakerDelete.as_view(), name='sneakers_delete'),
    path('sneakers/<int:sneaker_id>/add_cleaned/', views.add_cleaned, name='add_cleaned'),
    path('sneakers/<int:sneaker_id>/assoc_shoelace/<int:shoelace_id>/', views.assoc_shoelace, name='assoc_shoelace'),
    path('sneakers/<int:sneaker_id>/unassoc_shoelace/<int:shoelace_id>/', views.unassoc_shoelace, name='unassoc_shoelace'),
]

sneakercollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Shoelace(models.Model):
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color

    def get_absolute_url(self):
        return reverse('shoelace_detail', kwargs={'pk': self.id})

class Sneaker(models.Model):
    name = models.CharField(max_length=100)
    colorway = models.CharField(max_length=100)
    retail_price = models.IntegerField()
    shoelaces = models.ManyToManyField(Shoelace)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'sneaker_id': self.id})


class Cleaned(models.Model):
    date = models.DateField('Sneaker Cleaned Date')
    product = models.TextField(default="N/A")
    sneaker = models.ForeignKey(Sneaker, on_delete=models.CASCADE)

    def __str__(self):
        return f"Cleaned {self.sneaker.name} on {self.date} with {self.product}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Cleaned

class CleanedForm(ModelForm):
    class Meta:
        model = Cleaned
        fields = ['date', 'product']

main_app/views.py
from django.shortcuts import render, redirect
from .forms import CleanedForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Sneaker, Shoelace


# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def sneakers_index(request):
    sneakers = Sneaker.objects.all()
    return render(request, 'sneakers/index.html', {
        'sneakers': sneakers
    })

def sneakers_detail(request, sneaker_id):
    sneaker = Sneaker.objects.get(id=sneaker_id)
    
    id_list = sneaker.shoelaces.all().values_list('id')
    laces_sneaker_doesnt_have = Shoelace.objects.exclude(id__in=id_list)

    cleaned_form = CleanedForm()

    return render(request, 'sneakers/detail.html', {
        'sneaker': sneaker, 'cleaned_form': cleaned_form,
        'shoelaces': laces_sneaker_doesnt_have
    })


def add_cleaned(request, sneaker_id):
    form = CleanedForm(request.POST)
    if form.is_valid():
        new_cleaned = form.save(commit=False)
        new_cleaned.sneaker_id = sneaker_id
        new_cleaned.save()
    return redirect('detail', sneaker_id = sneaker_id)


def assoc_shoelace(request, sneaker_id, shoelace_id):
    Sneaker.objects.get(id=sneaker_id).shoelaces.add(shoelace_id)
    return redirect('detail', sneaker_id=sneaker_id)

def unassoc_shoelace(request, sneaker_id, shoelace_id):
    Sneaker.objects.get(id=sneaker_id).shoelaces.remove(shoelace_id)
    return redirect('detail', sneaker_id=sneaker_id)


class SneakerCreate(CreateView):
    model = Sneaker
    fields = ['name', 'colorway', 'retail_price']
    success_url = '/sneakers'

class SneakerUpdate(UpdateView):
    model = Sneaker
    fields = ['name', 'colorway', 'retail_price']


class SneakerDelete(DeleteView):
    model = Sneaker
    success_url = '/sneakers'



class ShoelaceList(ListView):
    model = Shoelace

class ShoelaceDetail(DeleteView):
    model = Shoelace

class ShoelaceCreate(CreateView):
    model = Shoelace
    fields = '__all__'

class ShoelaceUpdate(UpdateView):
    model = Shoelace
    fields = ['color']

class ShoelaceDelete(DeleteView):
    model = Shoelace
    success_url = '/shoelaces'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Sneaker Collector</h1>
    <hr>
    <p>This is a website that is perfect for keeping track of the sneakers you own!</p>
    <footer>All Rights Reserved, © 2022 Sneaker Collector</footer>
    
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Sneaker Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">  Sneaker Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'sneakers_create' %}">Add a pair of Sneakers</a></li>
          <li><a href="{% url 'index' %}">View All My Sneakers</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, © 2021 Sneaker Collector  </div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/sneaker_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>Delete Sneaker</h1>
<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' sneaker.id %}">Cancel</a>
  </form>

<h4></h4>

{% endblock %}

main_app/templates/main_app/sneaker_form.html
{% extends 'base.html'%}
{% block content %}

<h1>Add Sneaker</h1>
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/sneakers/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Sneaker Details</h1>

<div class="row">
  <div class="card">
      <div class="card-content">
          <span class="card-title">{{ sneaker.name }}</span>
          <p>Colorway: {{ sneaker.colorway }}</p>
          <p>Retaul Price: {{ sneaker.retail_price }}</p>
      </div>
      <div class="card-action">
          <a href="{% url 'sneakers_update' sneaker.id %}">Edit</a>
          <a href="{% url 'sneakers_delete' sneaker.id %}">Delete</a>
      </div>
  </div>


  <div class="col s6">
      <form action="{% url 'add_cleaned' sneaker.id %}" method="POST">
          {% csrf_token %}
          <!-- Render the inputs -->
          {{ cleaned_form.as_p }}
          <input type="submit" class="btn" value="Add Cleaning">
      </form>
      <table class="striped">
        <thead>
          <tr><th>Date</th><th>Cleaning Product</th></tr>
        </thead>
        <tbody>
          {% for cleaned in sneaker.cleaned_set.all %}
            <tr>
              <td>{{cleaned.date}}</td>
              <td>{{cleaned.product}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div> 
  </div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ sneaker.name }}'s Shoelaces</h3>
    {% if sneaker.shoelaces.count %}
      {% for shoelace in sneaker.shoelaces.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A pair of <span style="color: {{ shoelace.color }}">{{ shoelace.color }}</span> laces.
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_shoelace' sneaker.id shoelace.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No New Shoelaces added Yet</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
</div>

<div class="col s6">
  <h3>Available Shoelaces</h3>
  {% if shoelaces.count %}
    {% for shoelace in shoelaces.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            A pair of<span style="color: {{ shoelace.color }}">{{ shoelace.color }}</span> laces.
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_shoelace' sneaker_id shoelace_id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h5>{{sneaker.name}} Already Has All Laces Available</h5>
  {% endif %}
</div>

<script>
    const dateEl = document.getElementById('id_date');
    // M is Materialize's global variable
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
</script>

{% endblock %}

main_app/templates/sneakers/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Sneaker List</h1>

{% for sneaker in sneakers %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ sneaker.name }}</span>
      <p>Colorway: {{ sneaker.colorway }}</p>
      <p>Retaul Price: {{ sneaker.retail_price }}</p>
    </div>
  </div>
{% endfor %}

{% endblock %}